-- Добавляем все недостающие колонки
ALTER TABLE movies ADD COLUMN IF NOT EXISTS rated VARCHAR(10);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS released VARCHAR(20);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS writer TEXT;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS language VARCHAR(100);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS country VARCHAR(100);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS actors TEXT;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS awards TEXT;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS metascore VARCHAR(10);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS imdb_votes VARCHAR(20);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS type VARCHAR(20);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS dvd VARCHAR(20);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS box_office VARCHAR(50);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS production VARCHAR(100);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS website VARCHAR(200);