ALTER TABLE user_preferences
    ADD COLUMN IF NOT EXISTS thriller_pref DECIMAL(3,2) DEFAULT 0.50,
    ADD COLUMN IF NOT EXISTS romance_pref DECIMAL(3,2) DEFAULT 0.50,
    ADD COLUMN IF NOT EXISTS scifi_pref DECIMAL(3,2) DEFAULT 0.50,
    ADD COLUMN IF NOT EXISTS horror_pref DECIMAL(3,2) DEFAULT 0.50;